name: Auto Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.DATE }}
          name: "Auto Release ${{ env.DATE }}"
          body: "Automatic Release ${{ env.DATE }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
